### PR TITLE
Rephrase ban message

### LINKED ISSUE #489: Rephrase ban message sent to users
## Description of bug / unexpected behavior

The ban message sounds slightly off since it uses both second- and third-person pronouns.

## Expected behavior

The ban message can be rephrased to entirely use second-person pronouns.

## How to reproduce the issue

Ban someone from the server.

## Additional media files

Part of the ban message sent to users:
image

### PR DESCRIPTION
**Pull request by siumairice**
## Summary of Changes
Rephrased ban message, first pr. 

## Related Issues
Resolves #489.

### CODE REVIEW

File: src/components/admin.ts [hunk 1]
```diff
@@ -8,7 +8,7 @@ const MOD_USER_ID_FOR_BAN_APPEAL: string = vars.MOD_USER_ID_FOR_BAN_APPEAL;
 const makeBanMessage = (reason: string, days?: number): string =>
   `
 Uh oh, you have been banned from the UW Computer Science Club server ${
-    days ? `and deleted their messages in the past ${days} days ` : ``
+    days && `and your messages in the past ${days} days has been deleted`
```
Comment (Picowchew) [inline src/components/admin.ts:11]: `has` -> `have`

Also, while you're at it, it might be worthwhile to use the `pluralize` helper function in the `utils` folder for `days`.

**Review by Picowchew — CHANGES_REQUESTED** [review]
Thanks for your work! I left a minor comment.

File: src/components/admin.ts (hunk 1 above)
Comment (siumairice) [reply src/components/admin.ts]: hello! thank you for the feedback <3 I added the changes you suggested

**Review by Picowchew — APPROVED** [review]
LGTM! :)

**Review by mcpenguin — APPROVED** [review]
LGTM!
