### PR TITLE
Fixed position #0 in coin leaderboard

### LINKED ISSUE #419: Some users get #0 in coin leaderboard
## Description of bug / unexpected behavior

Some users have a rank of #0 when doing the coin leaderboard command, which should not happen.

Examples:
- https://discord.com/channels/667823274201448469/762882537692332064/1055683465238040576
- https://discord.com/channels/667823274201448469/762882537692332064/1055631675620597780

## Expected behavior

The rank of the user should be correctly displayed.

### PR DESCRIPTION
**Pull request by Picowchew**
## Summary of Changes

- Fixed the bug where a user who is not on the coin leaderboard would have position #0
- Stylized `CodeyCoin` as `Codey coin`
- Removed the word "current" from the naming related to the coin leaderboard; if more leaderboards are to be added later, then adjectives can be added just for those

## Motivation and Explanation

This fix would let a user see their correct position

## Related Issues

Resolves #419 

## Steps to Reproduce

Try `.coin lb` when you are not on the coin leaderboard

## Demonstration of Changes

Without ties:
image

With ties:
image

### CODE REVIEW

File: src/components/coin.ts [hunk 1]
```diff
@@ -146,16 +146,17 @@ export const changeDbCoinBalanceByUserId = async (
...
-export const getCurrentCoinLeaderboard = async (limit = 10): Promise<UserCoinEntry[]> => {
+export const getCoinLeaderboard = async (limit: number, offset = 0): Promise<UserCoinEntry[]> => {
   const db = await openDB();
   const res = await db.all(
     `
       SELECT user_id, balance
       FROM user_coin
       ORDER BY balance DESC
-      LIMIT ?
+      LIMIT ? OFFSET ?
```
Comment (mcpenguin) [inline src/components/coin.ts:156]: Can we split this into two separate lines?

**Review by mcpenguin — CHANGES_REQUESTED** [review]
Looks good, just had a small change.

**Review by mcpenguin — APPROVED** [review]
Upon further research, it seems that LIMIT and OFFSET are usually on the same line. So this PR looks good to me now!
